### ISSUE TITLE
event membership?

### ISSUE THREAD

**Issue by cjavdev** [trippdavis/CleatUp#6]
I respect that you're working in a polymorphic association and i like that. I'm not sure if this is the right fit tho. It feels a bit forced? maybe you're a member of groups, but then you have rsvp's for events?

I'm sure that the actual meetup has a distinction between the two. maybe make on table GroupMemberships and another table EventReservation or something that way you can be in a group that's putting on many events and you can rsvp to some of them...

What do you think?

**Comment by trippdavis** [comment]
Sounds good, probably will make things a little clearer and more straight forward.
